"""add_event

Revision ID: 1ba6fa8d2ea9
Revises: 399f1a60ba8f
Create Date: 2013-11-26 02:36:54.780724

"""

# revision identifiers, used by Alembic.
revision = '1ba6fa8d2ea9'
down_revision = '399f1a60ba8f'

from alembic import op
import sqlalchemy as sa

def upgrade():
    op.add_column('event', sa.Column('active', sa.Boolean(), nullable=True, default=True))
    op.add_column('event', sa.Column('duedate_start_on', sa.Date()))
    op.add_column('event', sa.Column('duedate_stop_on', sa.Date()))
    op.add_column('event', sa.Column('start_on', sa.Date(), nullable=False, server_default=sa.func.now()))
    op.add_column('event', sa.Column('stop_on', sa.Date(), nullable=False, server_default=sa.func.now()))
    op.add_column('talk', sa.Column('event_id', sa.Integer()))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('talk', 'event_id')
    op.drop_column('event', 'stop_on')
    op.drop_column('event', 'start_on')
    op.drop_column('event', 'duedate_stop_on')
    op.drop_column('event', 'duedate_start_on')
    op.drop_column('event', 'active')
    ### end Alembic commands ###
