"""add_config_parameter

Revision ID: 399f1a60ba8f
Revises: 48eb0e3f4563
Create Date: 2013-11-25 22:32:54.660859

"""

# revision identifiers, used by Alembic.
revision = '399f1a60ba8f'
down_revision = '48eb0e3f4563'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configparameter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('value_string', sa.String(), nullable=True),
    sa.Column('value_integer', sa.Integer(), nullable=True),
    sa.Column('value_date', sa.Date(), nullable=True),
    sa.Column('value_datetime', sa.DateTime(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('configparameter')
    ### end Alembic commands ###
